### ISSUE TITLE
Configure topics and ACL via Zookeeper

### ISSUE THREAD

**Issue by Constantin07** [Mongey/terraform-provider-kafka#106]
Hi,

This is rather a question.

I'm using Amazon MSK Cluster and examples given here [create-topic](https://docs.aws.amazon.com/msk/latest/developerguide/create-topic.html) and here [msk-authentication](https://docs.aws.amazon.com/msk/latest/developerguide/msk-authentication.html) suggest to use Zookeeper nodes instead of broker nodes for topic & ACL management.

Does this provider support talking to Zookeeper nodes for the above actions instead of brokers ?

PS: I'm not a Kafka guru.

**Comment by cricket007** [comment]
FWIW, Creating topics doesn't require Zookeeper after Kafka 0.11

**Comment by Mongey** [comment]
> Does this provider support talking to Zookeeper nodes for the above actions instead of brokers ?

no, it's only supported via Kafka

**Comment by cricket007** [comment]
The Kafka Authorizor is pluggable as well. Zookeeper just happens to be the default.

OpenPolicyAgent is making developments in this space as well

**Comment by Constantin07** [comment]
@cricket007 Thanks for getting back. The reason is that I've seen in internet both ways - tested locally and they both work but cli tool mentions that managing via Zookeeper is going to be deprecated. That's why I got confused.

**Comment by Constantin07** [comment]
Thanks

**Comment by cricket007** [comment]
For context - https://cwiki.apache.org/confluence/display/KAFKA/KIP-500%3A+Replace+ZooKeeper+with+a+Self-Managed+Metadata+Quorum
