### ISSUE TITLE
Adding Cluster ACL permissions fails

### ISSUE THREAD

**Issue by Constantin07** [Mongey/terraform-provider-kafka#107]
On AWS MSK Kafka version `2.2.1` I'm trying to add Cluster permissions like this:
```hcl
resource "kafka_acl" "admin_cluster" {
  resource_name       = "*"
  resource_type       = "Cluster"
  acl_principal       = "User:CN=admin-user"
  acl_operation       = "All"
  acl_permission_type = "Allow"
  acl_host            = "*"
}
```

but getting back this error:
```
kafka_acl.admin_cluster: Creating...

Error: kafka server: This most likely occurs because of a request being malformed by the client library or the message was sent to an incompatible broker. See the broker logs for more details.

  on main.tf line 67, in resource "kafka_acl" "admin_cluster":
  67: resource "kafka_acl" "admin_cluster" {
```

When I do manually add the ACL using Kafka command line tools it works:
```bash
$ kafka-acls.sh --authorizer-properties zookeeper.connect="${ZOOKEEPER_NODES}" --add --allow-principal "User:CN=admin-user" --operation All --cluster
Adding ACLs for resource `Cluster:LITERAL:kafka-cluster`:
 	User:CN=admin-user has Allow permission for operations: All from hosts: *

Current ACLs for resource `Cluster:LITERAL:kafka-cluster`:
	User:CN=admin-user has Allow permission for operations: All from hosts: *

$
```

**Comment by endofcake** [comment]
For whatever reason, the name of the cluster is hard-coded in Kafka source code:
  # https://github.com/apache/kafka/blob/3cdc78e6bb1f83973a14ce1550fe3874f7348b05/clients/src/main/java/org/apache/kafka/common/resource/Resource.java#L37
 It's not required when setting ACLs from the command line, but apparently
  is needed for the Go library.
```terraform
  resource_name                = "kafka-cluster"
```

**Comment by Constantin07** [comment]
Thanks @endofcake for fast reply.  Does it mean that the mentioned `Cluster` in resource type in README.md is wrong ?

**Comment by endofcake** [comment]
Not sure I follow @Constantin07 . Why is `Cluster` resource_type is wrong? Have you tried the example above?

**Comment by Constantin07** [comment]
Thanks @endofcake. It worked!

**Comment by kanthi-hpfc** [comment]
> For whatever reason, the name of the cluster is hard-coded in [Kafka source code](https://github.com/apache/kafka/blob/3cdc78e6bb1f83973a14ce1550fe3874f7348b05/clients/src/main/java/org/apache/kafka/common/resource/Resource.java#L37).
> 
> It's not required when setting ACLs from the command line, but apparently is needed for the Go library.
> 
> ```terraform
>   resource_name                = "kafka-cluster"
> ```
> 
> #90
> @Mongey , should this be treated as a special case? Provider could default to this resource name (and in fact make it optional), just for cluster-level ACLs.

What about confluent cloud? how can we specify a specific confluent cluster id then?
