### ISSUE TITLE
Unable to define ACL to allow Describe action on Cluster resource type

### ISSUE THREAD

**Issue by jaapterwoerds** [Mongey/terraform-provider-kafka#116]
I'm trying too setup a schema registry and want to define an ACL in which I Allow the schema registry user to use the Describe action on the Cluster resource. 

ACL definition
`
resource "acl" "example" {
  resource_name       = "*"
  resource_type       = "Cluster"
  acl_principal       = "User:registry"
  acl_host            = "*"
  acl_operation       = "Describe"
  acl_permission_type = "Allow"
}
`
Actual error:
`
Error: kafka server: This most likely occurs because of a request being malformed by the client library or the message was sent to an incompatible broker. See the broker logs for more details.

  on kafka-security.tf line 54, in resource "kafka_acl" "schema-registry-cluster-acl":
  54: resource "kafka_acl" "schema-registry-cluster-acl" {
}
`
As far as I can tell there is no resource name applicable for this ACL, so it might be the action to Kafka does actually render the * as resource name and rejects it.

From debug logging I get the following:
`
2020-05-01T10:15:54.704+0200 [DEBUG] plugin.terraform-provider-kafka_v0.2.4: 2020/05/01 10:15:54 [DEBUG] Creating ACL User:schema-registry|*|Describe|Allow|Cluster||Literal
2020-05-01T10:15:54.869+0200 [DEBUG] plugin.terraform-provider-kafka_v0.2.4: 2020/05/01 10:15:54 [ERROR] Failed to create ACL
2020/05/01 10:15:54 [DEBUG] kafka_acl.schema-registry-cluster-acl: apply errored, but we're indicating that via the Error pointer rather than returning it: kafka server: This most likely occurs because of a request being malformed by the client library or the message was sent to an incompatible broker. See the broker logs for more details.
`

**Comment by Constantin07** [comment]
@jaapterwoerds as resource name try to use `kafka-cluster` 
See https://github.com/Mongey/terraform-provider-kafka/issues/107 for more details.

**Comment by jaapterwoerds** [comment]
Thanks, I was searching in the issues but overlooked that one apparently. 

I will make a PR to at least update the doc in this repo with this gotcha.
