### ISSUE TITLE
Publish this provider to Terraform Registry

### ISSUE THREAD

**Issue by brunodomenici** [Mongey/terraform-provider-kafka#117]
Hi,

With Terraform Cloud we're not able to use providers not registered in Terraform Registry.
It could be great to this provider in Terraform Cloud.

Is it possible publish it there?

Thanks a lot!

**Comment by Mongey** [comment]
Hey @brunodomenici ...  I don't think it's possible to publish providers there at the moment, only modules?
It looks like there's some work underway in [terraform 0.13](https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md#0130-unreleased) to better deal with this

> Terraform now supports a decentralized namespace for providers, allowing for automatic installation of community providers from third-party namespaces in the public registry and from private registries. (More details will be added about this prior to release.)

**Comment by brunodomenici** [comment]
Hi,

You're right. Actually, the registry of community provider is on closed beta for now:

<img width="1160" alt="image" src="https://user-images.githubusercontent.com/12513750/81147512-bbeee880-8f7a-11ea-94d4-fd812051b2e2.png">

https://www.terraform.io/docs/registry/providers/docs.html

Let's wait!
Thank you!
