### ISSUE TITLE
Unable to create topic in Azure HDInsight

### ISSUE THREAD

**Issue by q26646** [Mongey/terraform-provider-kafka#121]
Hi, 
I am running the below terraform script from a jumphost that is in the same VNet as HDInsight and I am getting the following error: 

> **Error: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)**

```
provider "kafka" {
bootstrap_servers= ["10.154.79.5:9092,10.154.79.6:9092,10.154.79.7:9092,10.154.79.8:9092"]
}

resource "kafka_topic" "logs" {
  name               = "bd-test-topic"
  replication_factor = 2
  partitions         = 100

  config = {
    "segment.ms"     = "20000"
    "cleanup.policy" = "compact"
  }
}
```
I have tested the connectivity using a python script on the same machine which works fine. Am I missing something?

**Comment by Mongey** [comment]
@q26646  `bootstrap_servers` takes a list of strings 
You might also need to disable tls.
```tf
provider "kafka" {
  bootstrap_servers = ["10.154.79.5:9092","10.154.79.6:9092","10.154.79.7:9092","10.154.79.8:9092"]
  tls_enabled = false
}
```

**Comment by q26646** [comment]
I tried the list of strings before and it did not work. But I was able to get it to work with tls_enabled..thanks for your help!
