### ISSUE TITLE
Can't import provider since 0.2.6

### ISSUE THREAD

**Issue by sdomeshok** [Mongey/terraform-provider-kafka#126]
Ever since 0.2.6 went live, when we run the provider we get:
```
Provider "kafka" not available for installation.
```
Confirmed regression since 0.2.5

We install the provider by dropping the binary in `~/.terraform.d/plugins/$( uname -s )`.

**Comment by yaronshemesh** [comment]
try change the file name to include "v" before the version
it suppose to be in this format: terraform-provider-<NAME>_vX.Y.Z (see [here](terraform-provider-<NAME>_vX.Y.Z))

**Comment by GuilhermeBarile** [comment]
I can confirm that adding `v` to the filename as @yaronshemesh suggested works

**Comment by Mongey** [comment]
This is a bug, I updated the release script to conform to the the suggested values when publishing [to the terraform registry][registry] which is coming in `terraform 0.13`
I'll check to see if adding back the `v` to the binary is compatible with everything.

[registry]: https://registry.terraform.io/providers/Mongey/kafka/latest
