### ISSUE TITLE
Terraform Registry release anytime soon?

### ISSUE THREAD

**Issue by larsomat** [Mongey/terraform-provider-kafka#132]
Hello there,
thanks for the ongoing support of Kafka via your provider, we are using it currently without much problems  in Terraform Cloud, but we are wondering if there are any plans to release it to the terraform registry any time soon? We suffer some degraded timing because of the additional plugin binaries in the repository.

Best regards,
Lars

**Comment by Mongey** [comment]
👋 we're already [there](https://registry.terraform.io/providers/Mongey/kafka/latest) 😀

```hcl 
terraform {
  required_providers {
    kafka = {
      source = "Mongey/kafka"
      version = "0.2.7"
    }
  }
}

```

**Comment by drobakowski** [comment]
Hi @Mongey, nice, thanks for the update! Is there any need for terraform `0.13`? As this is a preview version, this is not available on Terraform Cloud so far...
<img width="310" alt="image" src="https://user-images.githubusercontent.com/81381/85562914-36f48700-b62d-11ea-8f21-ea9a78f02005.png">

**Comment by Mongey** [comment]
@drobakowski 0.13 is required if you want Terraform to automatically download the provider -- otherwise the [normal procedure](https://www.terraform.io/docs/cloud/run/install-software.html#custom-and-community-providers) applies

**Comment by drobakowski** [comment]
Ah ok, I see. Thanks @Mongey. So let's see when `0.13` will be available on TFC... :)

**Comment by Mongey** [comment]
I'm going to close this -- this has been done, and every release now gets published to the registry.
