### ISSUE TITLE
Adding partitions recreates the topic

### ISSUE THREAD

**Issue by vinceprignano** [Mongey/terraform-provider-kafka#14]
```
-/+ kafka_topic.test (new resource required)
      id:                     "test" => <computed> (forces new resource)
      config.%:               "0" => "2"
      config.retention.bytes: "" => "107374182400"
      config.retention.ms:    "" => "604800001"
      name:                   "test" => "test"
      partitions:             "50" => "55" (forces new resource)
      replication_factor:     "3" => "3"
```
It seems that adding partitions tries to recreate the topic. Is there any way in Sarama to have this operation to be in place?

**Comment by Mongey** [comment]
👋  @vinceprignano It looks like Sarama does support [adding partitions to a topic](https://github.com/Shopify/sarama/blob/1abfd988367f6686e39dd618998a037d41b46f36/request.go#L128)

I should be able to make increasing partitions non-destructive, but decreasing partitions will continue to force a new resource, as there is no support in the Kafka API for deleting partitions.

**Comment by vinceprignano** [comment]
Awesome! :)

**Comment by vinceprignano** [comment]
@Mongey any progress on this?

**Comment by Mongey** [comment]
@vinceprignano Not yet, I'll pick this up,in the next few weeks if I get some time.
