### ISSUE TITLE
terraform 0.13 can't find provider, probably because it gets lowercased

### ISSUE THREAD

**Issue by wasilak** [Mongey/terraform-provider-kafka#142]
In both GitHub issues and on registry.terraform.io page there is info to use capitalised name of provider (`Mongey/kafka:`), but terraform `0.13` can't find it and shows that it looks for lowercased version (`mongey/kafka:`)... 

This is my config:
```
required_providers {
    kafka = {
      source = "Mongey/kafka"
      version = "0.2.9"
    }
  }
```

and TF output:

```
Initializing provider plugins...
- terraform.io/builtin/terraform is built in to Terraform
- Using previously-installed hashicorp/aws v3.1.0
- Using previously-installed -/aws v3.1.0
- Finding latest version of mongey/kafka...

Error: Failed to install provider

Error while installing mongey/kafka v0.2.9: could not query provider registry
for registry.terraform.io/mongey/kafka: failed to retrieve authentication
checksums for provider: 404 Not Found
```

Not sure if it can be addressed by you by lowercasing it or should be handled by Terraform support.

Right now it simply blocks us from using your provider.

Thanks!
Peter

**Comment by Mongey** [comment]
👋 Hey @wasilak  ... this seems like a Terraform issue, rather than the provider. 
I'm not sure what I could do to fix this on my side other than change my username.

**Comment by wasilak** [comment]
I was afraid that it would be the case... sorry for bothering you. I suspected that username change won't be an option ;) 

Thanks!

**Comment by Mongey** [comment]
Oh. Actually. Looks like the lower casing is a red herring. It's looking for the checksums to be named differently.

```
Initializing provider plugins...
2020/08/11 13:58:33 [TRACE] providercache.fillMetaCache: scanning directory .terraform/plugins
2020/08/11 13:58:33 [DEBUG] Service discovery for registry.terraform.io at https://registry.terraform.io/.well-known/terraform.json
2020/08/11 13:58:33 [TRACE] HTTP client GET request to https://registry.terraform.io/.well-known/terraform.json
- Finding mongey/kafka versions matching "0.2.9"...
2020/08/11 13:58:33 [DEBUG] GET https://registry.terraform.io/v1/providers/mongey/kafka/versions
2020/08/11 13:58:33 [TRACE] HTTP client GET request to https://registry.terraform.io/v1/providers/mongey/kafka/versions
2020/08/11 13:58:34 [DEBUG] GET https://registry.terraform.io/v1/providers/mongey/kafka/0.2.9/download/darwin/amd64
2020/08/11 13:58:34 [TRACE] HTTP client GET request to https://registry.terraform.io/v1/providers/mongey/kafka/0.2.9/download/darwin/amd64
2020/08/11 13:58:34 [DEBUG] GET https://github.com/Mongey/terraform-provider-kafka/releases/download/v0.2.9/terraform-provider-kafka_0.2.9_SHA256SUMS
2020/08/11 13:58:34 [TRACE] HTTP client GET request to https://github.com/Mongey/terraform-provider-kafka/releases/download/v0.2.9/terraform-provider-kafka_0.2.9_SHA256SUMS

Error: Failed to install provider

Error while installing mongey/kafka v0.2.9: could not query provider registry
for registry.terraform.io/mongey/kafka: failed to retrieve authentication
checksums for provider: 404 Not Found
```

**Comment by wasilak** [comment]
oh, so maybe there is actually something to be done there, like renaming the checksums? :D

**Comment by wasilak** [comment]
I can see that it doesn't like `v` in version in filename, so it looks for `terraform-provider-kafka_0.2.9_SHA256SUMS` instead of `terraform-provider-kafka_v0.2.9_SHA256SUMS`

**Comment by Mongey** [comment]
@wasilak 
this seems to work

```terraform
terraform {
  required_providers {
    kafka = {
      source  = "Mongey/kafka"
      version = "0.2.10"
    }
  }
}
```

**Comment by wasilak** [comment]
works like a charm, big thanks! :)

**Comment by fereggert** [comment]
Same error with 0.4.2:
`2022-01-11T17:45:00.953-0300 [DEBUG] GET https://registry.terraform.io/v1/providers/mongey/kafka/0.4.2/download/linux/amd64
2022-01-11T17:45:00.954-0300 [TRACE] HTTP client GET request to https://registry.terraform.io/v1/providers/mongey/kafka/0.4.2/download/linux/amd64
2022-01-11T17:45:01.239-0300 [DEBUG] GET https://github.com/Mongey/terraform-provider-kafka/releases/download/v0.4.2/terraform-provider-kafka_0.4.2_SHA256SUMS
2022-01-11T17:45:01.239-0300 [TRACE] HTTP client GET request to https://github.com/Mongey/terraform-provider-kafka/releases/download/v0.4.2/terraform-provider-kafka_0.4.2_SHA256SUMS
2022-01-11T17:45:11.241-0300 [ERROR] GET https://github.com/Mongey/terraform-provider-kafka/releases/download/v0.4.2/terraform-provider-kafka_0.4.2_SHA256SUMS request failed: Get "https://github.com/Mongey/terraform-provider-kafka/releases/download/v0.4.2/terraform-provider-kafka_0.4.2_SHA256SUMS": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
2022-01-11T17:45:11.241-0300 [DEBUG] GET https://github.com/Mongey/terraform-provider-kafka/releases/download/v0.4.2/terraform-provider-kafka_0.4.2_SHA256SUMS: retrying in 1s (1 left)
2022-01-11T17:45:12.241-0300 [INFO]  Previous request to the remote registry failed, attempting retry.
2022-01-11T17:45:12.241-0300 [TRACE] HTTP client GET request to https://github.com/Mongey/terraform-provider-kafka/releases/download/v0.4.2/terraform-provider-kafka_0.4.2_SHA256SUMS
2022-01-11T17:45:22.242-0300 [ERROR] GET https://github.com/Mongey/terraform-provider-kafka/releases/download/v0.4.2/terraform-provider-kafka_0.4.2_SHA256SUMS request failed: Get "https://github.com/Mongey/terraform-provider-kafka/releases/download/v0.4.2/terraform-provider-kafka_0.4.2_SHA256SUMS": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

╷
│ Error: Failed to install provider
│
│ Error while installing mongey/kafka v0.4.2: could not query provider registry for registry.terraform.io/mongey/kafka: failed to retrieve
│ authentication checksums for provider: the request failed after 2 attempts, please try again later: Get
│ "https://github.com/Mongey/terraform-provider-kafka/releases/download/v0.4.2/terraform-provider-kafka_0.4.2_SHA256SUMS": net/http: request canceled
│ while waiting for connection (Client.Timeout exceeded while awaiting headers)`

**Comment by fereggert** [comment]
It was a DNS problem in my case. 
DNS was resolving, but to slow, changed to DNS from Google and worked.

**Comment by JoshTRN** [comment]
@fereggert How did you change the DNS? I'm getting this same issue and I'm convinced that it's a connection speed issue due to the fact that when I run `terrafrom init` locally when the vpn is on, it doesn't work, but when I turn off my vpn it does. 

My CI/CD pipeline is having the same issue so I need to resolve it, the trouble is I'm not sure how to change the DNS.

**Comment by fereggert** [comment]
> @fereggert How did you change the DNS? I'm getting this same issue and I'm convinced that it's a connection speed issue due to the fact that when I run `terrafrom init` locally when the vpn is on, it doesn't work, but when I turn off my vpn it does.
> 
> My CI/CD pipeline is having the same issue so I need to resolve it, the trouble is I'm not sure how to change the DNS.

@JoshTRN you change it at your network configuration, it's not a Terraform config, it's on your O.S.

**Comment by JoshTRN** [comment]
Thanks. I ended up changing the proxy configuration on the docker image that was running terraform and that fixed everything.
