### ISSUE TITLE
terraform init with v0.13 fails

### ISSUE THREAD

**Issue by kaushiksriram100** [Mongey/terraform-provider-kafka#144]
When I use this plugin with terraform 0.13, I get an error - 

Somehow, `init` attempts to download from `hashicorp/kafka` despite successfully finding the plugin in `mongey/kafka`. 
Any pointers? 
```
Initializing provider plugins...
- Finding mongey/kafka versions matching "0.2.10"...
- Finding latest version of hashicorp/kafka...
- Installing mongey/kafka v0.2.10...
- Installed mongey/kafka v0.2.10 (self-signed, key ID 5C886ACC44EB17C0)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/plugins/signing.html

Error: Failed to install provider

Error while installing hashicorp/kafka: provider registry
registry.terraform.io does not have a provider named
registry.terraform.io/hashicorp/kafka
```

**Comment by cajbecu** [comment]
+1

**Comment by Mongey** [comment]
can you provide the full config you're using ?

**Comment by endofcake** [comment]
I was seeing the same problem, in my case it happened only when I used modules.
Can you give the output of `terraform providers` @kaushiksriram100 ?

**Comment by cajbecu** [comment]
@endofcake thanks for the hint

@kaushiksriram100 I was able to make it work: 
```
❯ cat versions.tf
terraform {
  required_providers {
    kafka = {
      source = "Mongey/kafka"
    }
  }
  required_version = ">= 0.13"
}
```

```
❯ cat kafka.tf
provider "kafka" {
  bootstrap_servers = ["broker:9092"]
}

resource "kafka_topic" "test-logs" {
  name               = "systemd_logs"
  replication_factor = 2
  partitions         = 3

  config = {
    "segment.ms"     = "20000"
    "cleanup.policy" = "compact"
  }
}
```

`terraform init` works now

**Comment by kaushiksriram100** [comment]
> I was seeing the same problem, in my case it happened only when I used modules.
> Can you give the output of `terraform providers` @kaushiksriram100 ?

Yes, that is right. I think I was able to figure out - 
If we use child modules, then we have to declare the `required_providers` for each module separately in each module. I wasn't declaring again, resulting in terraform constructing the invalid hashicorp/kafka URL for resource "kafka_topic". 

From terraform documentation for v0.13 (apologies, should have read it before opening a case) - 
```
Each Terraform module must declare which providers it requires, so that Terraform can install and use them. Provider requirements are declared in a required_providers block
```

**Comment by kaushiksriram100** [comment]
This issue can be closed.
