### ISSUE TITLE
Feature request: Proxying

### ISSUE THREAD

**Issue by MadsRC** [Mongey/terraform-provider-kafka#147]
It happens, somewhat frequently, that I need to manage a Kafka cluster, one which cannot be connected directly to. I'd prefer to manage the cluster using Terraform, but since no Kafka providers support any form of proxying, this isn't really possible.

Looking at the underlying library used here, I see that Sarama's [Config object](https://godoc.org/github.com/Shopify/sarama#Config) supports proxying by way of the [proxy.Dialer](https://godoc.org/golang.org/x/net/proxy#Dialer).

It would be awesome to be able to override Sarama's Config object, in order to provide proxy support.

Is this something that would be accepted into the codebase of this provider?
If so, I'd very much like to donate time to build it!

**Comment by Mongey** [comment]
I think that's something reasonable to support... I don't have the time to add this myself, but a PR is welcome 😄

**Comment by MadsRC** [comment]
Great, I'll experiment a bit with it and come up with a MVP in a PR ;)

**Comment by MadsRC** [comment]
It seems like it wouldn't be too much trouble implementing it. The only issue I'm having with it is that I can't get the upstream acceptance tests to run successfully under MacOS using Docker Desktop for Mac... Tracking it down, it seems to be an TLS authentication issue.

Am I right to assume the tests have never been run on MacOS?
Might have time to try running the tests from a Linux host during the weekend... Knowing the tests will run successfully prior to writing any code is kinda nice...

**Comment by jhiller** [comment]
One way to do this is to use a kafka-aware proxy and point your bootstrap server setting at it.   Deploy the proxy somewhere that has connectivity to the cluster.

https://github.com/grepplabs/kafka-proxy

**Comment by Mongey** [comment]
> It seems like it wouldn't be too much trouble implementing it. The only issue I'm having with it is that I can't get the upstream acceptance tests to run successfully under MacOS using Docker Desktop for Mac... Tracking it down, it seems to be an TLS authentication issue.

@MadsRC tbh the TLS setup here is a bit of a mess, but whatever setup I have locally seems pass -- I'm using macOS + docker too. CI passes too. Is there an error you're getting ?
