### ISSUE TITLE
Any AWS MSK Examples?

### ISSUE THREAD

**Issue by danbosnichill** [Mongey/terraform-provider-kafka#154]
Hi!  This is a feature request (not an issue).

Are there any example setups where "kafka_topic" is used with MSK?

Thanks!
- Dan

**Comment by haidaraM** [comment]
We are using this provider successfully with AWS MSK. Nothing special when using MSK, you just need to provide the correct parameters to the provider. 

Here is an example with a cluster in 3 availability zones
```hcl
provider "kafka" {
    bootstrap_servers = [
     "b-1.cluster-name.xxxx.c2.kafka.eu-west-1.amazonaws.com:9094",
     "b-2.cluster-name.xxxx.c2.kafka.eu-west-1.amazonaws.com:9094",
     "b-3.cluster-name.xxxx.c2.kafka.eu-west-1.amazonaws.com:9094"
    ]
    tls_enabled       = true
}

# Define your topics here...
```

**Comment by rssaini01** [comment]
It shows, the provider is communicating through the TLS with broker, and the port 9094 is not enabled in MSK Cluster.

Is there any configuration to communicate through the SASL/SCARM with the broker to create the topic?

Thanks!
