### ISSUE TITLE
Plan fails because "The replica count isn't the same across partitions 3 != 4"

### ISSUE THREAD

**Issue by cojamac** [Mongey/terraform-provider-kafka#157]
And sure enough, one of the partitions on the topic has a 4th replica. I'm not sure this is a problem though. It seems odd but maybe it's ok. I'm using a confluent cloud enterprise account for what it's worth.

I found the code and it appears that the function exists to provide the current replication factor for a topic. It does this by counting the number of replicas on each partition. It produces an error if the number of replicas isn't the same for each partition.

I do not understand why a 4th replica has appeared for the one partition. I haven't dug deep enough into Kafka to understand why this might happen but it does seem fairly benign. Perhaps it would be good enough that this function returned the minimum number of replicas across partitions and was not too concerned with an extra replica here or there. 

https://github.com/Mongey/terraform-provider-kafka/blob/f188c53e3581901a106c8983b72e663994bffb59/kafka/topic.go#L27-L47

**Comment by Mongey** [comment]
@cojamac I'm not really sure what else the provider can do here. 
I think implementing the min of the partitions would cause other issues.

**Comment by cojamac** [comment]
I think you might be right about other problems. I've done some more reading this morning and it seems like this is the best we can do to determine the current replication factor from the cluster. It looks like Sarama added support for partition reassignments in May and there is an PR in the works to support that in this project. I believe that code would resolve this situation so it's probably just a matter of shorting this error condition if the replication factor can be modified. I'm going to follow up on that PR.

https://github.com/Mongey/terraform-provider-kafka/issues/53

**Comment by ntrvic** [comment]
@cojamac just wanted to check in on this issue. I hit the same problem, and was not able to resolve with v0.3.3 of the plugin. The extra replicas on some partition issues happened to us after a partition rebalance. Did you ever get around it?

**Comment by cojamac** [comment]
We needed to fix the problem manually. https://docs.confluent.io/platform/current/kafka/post-deployment.html#increasing-replication-factor

**Comment by ntrvic** [comment]
Same here. Thanks for the update @cojamac
