### ISSUE TITLE
server misbehaving when planing via sshuttle or VPN

### ISSUE THREAD

**Issue by dimisjim** [Mongey/terraform-provider-kafka#162]
Hey there,

I have a vanilla kafka cluster which runs inside a private network. In order to be able to plan and for the provider to be able to communicate with the cluster, I use sshuttle.

I am getting though this error, when planning for a particular topic:

`Error: dial tcp: lookup <privIPofaBroker> on 127.0.0.53:53: server misbehaving`

`<privIPofaBroker>` is always the same and is the controller of the cluster.

Any clues? The broker itself runs fine, and the plan runs as expected when it's ran from inside the private network.

Running on provider v0.2.10 and kafka v1

**Comment by dimisjim** [comment]
forced a new controller election and the issue still persists, but it how prints the new controller as the one that misbehaves.

**Comment by dimisjim** [comment]
I have tried agai with controller a broker that has little cpu load (20%), but I am still getting this error.

**Comment by Mongey** [comment]
I would suggest running terraform within the private network, rather than via an ssh tunnel.
Please see https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/

**Comment by dimisjim** [comment]
@Mongey getting the same error when using a VPN connection.

**Comment by dimisjim** [comment]
Ok, problem solved, it was a matter of adding the `<privIPofaBroker>` that was outputted in the error (it was in the form of ip-x-x-x-x) in my `etc/hosts` file. That's because of how advertised.listeners is configured which was is in the PLAINTEXT://ip-x-x-x-x:9092

So with the /etc/hosts entry (or with a proper x.x.x.x ip for advrtised.listeners) it should work for both sshuttle and VPN.
