### ISSUE TITLE
Error while installing hashicorp/kafka: provider registry does not have the name..

### ISSUE THREAD

**Issue by micha-bitton-walkme** [Mongey/terraform-provider-kafka#169]
Hi,

I'm trying to configure "kafka" provider and call to "topic" module.

however i'm receving the following error message:

Error: Failed to install provider
Error while installing hashicorp/kafka: provider registry
registry.terraform.io does not have a provider named
registry.terraform.io/hashicorp/kafka

From debug I can see that he already download the required provider however it's keep failing:

Initializing provider plugins...
- Using previously-installed mongey/kafka v0.3.0
- terraform.io/builtin/terraform is built in to Terraform
- Finding latest version of hashicorp/kafka...
2021/03/17 16:52:22 [DEBUG] Service discovery for registry.terraform.io at https://registry.terraform.io/.well-known/terraform.json
2021/03/17 16:52:23 [WARN] Log levels other than TRACE are currently unreliable, and are supported only for backward compatibility.
  Use TF_LOG=TRACE to see Terraform's internal logs.
  ----
2021/03/17 16:52:23 [DEBUG] GET https://registry.terraform.io/v1/providers/hashicorp/kafka/versions
2021/03/17 16:52:23 [WARN] Log levels other than TRACE are currently unreliable, and are supported only for backward compatibility.
  Use TF_LOG=TRACE to see Terraform's internal logs.
  ----
2021/03/17 16:52:23 [DEBUG] GET https://registry.terraform.io/v1/providers/-/kafka/versions
"

I tried also to "replace-provider" in the state for all the modules:
terraform13 state replace-provider registry.terraform.io/-/kafka registry.terraform.io/mongey/kafka

Not sure why he still going to find "hashicorp/kafka" 
```tf
terraform provider.tf:
terraform {
  required_providers {
    kafka = {
      source = "Mongey/kafka"
      version = "0.3.0"
    }
  }
}

provider "kafka" {
  bootstrap_servers = ["${split(",", data.terraform_remote_state.insights_cluster.bootstrap_brokers)}"]
}


module "kafka_topic_1" {
  source       = "git@github.com:<xxxx>//kafka_topic"
  topic_name   = "xxx"
  max_msg_size = "3000000000"
}

inside the module:
"
resource "kafka_topic" "topic" {
  name               = "${var.topic_name}"
  replication_factor = "${var.replication_factor}"
  partitions         = "${var.partitions_count}"

  config = {
    "max.message.bytes"    = "${var.max_msg_size}"
    "retention.ms"         = "${var.retention_ms}"
    "delete.retention.ms"  = "${var.delete_retention_ms}"
  }
}
```

any clue what else can be the issue?

**Comment by Mongey** [comment]
I think this is more of a terraform question, but perhaps you need something like

```
terraform13 state replace-provider registry.terraform.io/hashicorp/kafka registry.terraform.io/mongey/kafka
```

**Comment by micha-bitton-walkme** [comment]
Already tried that.
terraform13 state replace-provider registry.terraform.io/hashicorp/kafka registry.terraform.io/mongey/kafka
**No matching resources found.**

**Comment by samhandev** [comment]
I'm getting the same issue when you have `kafka_` resources in a module that I've `source'd.

Seems to work fine if you don't use it via a module though!

**Comment by samhandev** [comment]
@micha-bitton-walkme 
you might need
```
terraform {
  required_providers {
    kafka = {
      source = "Mongey/kafka"
      version = "0.3.0"
    }
  }
}
```

in the `git@github.com:<xxxx>//kafka_topic` repo. We added this in a `main.tf` and `terraform init` worked fine.

**Comment by micha-bitton-walkme** [comment]
@samhandev just tried it and it's doesn't work either:

In the module, under the "main.tf" file i have the following configuration:
"
resource "kafka_topic" "topic" {
  name               = "${var.topic_name}"
  replication_factor = "${var.replication_factor}"
  partitions         = "${var.partitions_count}"

  config = {
    "max.message.bytes"    = "${var.max_msg_size}"
    "retention.ms"         = "${var.retention_ms}"
    "delete.retention.ms"  = "${var.delete_retention_ms}"
  }
}

terraform {
  required_providers {
    kafka = {
      source = "Mongey/kafka"
      version = "0.3.0"
    }
  }
}

"

and still i'm receiving the same error message, not sure why he always goes to "namespace" "hashicorp".
