### ISSUE TITLE
Issue with new 0.3.0 version.

### ISSUE THREAD

**Issue by macktab** [Mongey/terraform-provider-kafka#170]
Hello.

I have got some errors with new 0.3.0 version (also got similar with 0.2.5):

Here is my test template:

```tf
variable "aws_region" { default = "us-east-1" }
variable "vpc" { default = "preprod" }
variable "brokers_lookup" {
  default = {
    "us-east-1.dev" = [
      "kf0001.cf.prd349.dev3.test.local:9092",
      "kf0002.cf.prd349.dev3.test.local:9092",
    ]
    "us-east-1.preprod" = "kf0001.cf.prd349.preprod3.test.local:9092,kf0002.cf.prd349.preprod3.test.local:9092"
  }
}

terraform {
  required_providers {
    kafka = {
      source = "Mongey/kafka"
      version = "0.2.12"
    }
  }
}

provider "kafka" {
  bootstrap_servers = tolist([var.brokers_lookup[format("%s.%s",var.aws_region,var.vpc)]])
}

resource "kafka_topic" "connect_config" {
  name               = "connect-tests"
  replication_factor = 3
  partitions         = 1

  config = {
    "segment.ms"     = "20000"
    "cleanup.policy" = "compact"
  }
}
```

If I try to use latest version, then I got this error:
`Error: dial tcp: address kf0001.cf.prd349.preprod3.test.local:9092,kf0002.cf.prd349.preprod3.test.local:9092: too many colons in address kafka: client has run out of available brokers to talk to (Is your cluster reachable?)`
If it 0.2.12, then everything looks OK.

**Comment by Mongey** [comment]
@macktab your pre-prod environment should have brokers as a list, not a string.

```tf
variable "brokers_lookup" {
  default = {
    "us-east-1.dev" = [
      "kf0001.cf.prd349.dev3.test.local:9092",
      "kf0002.cf.prd349.dev3.test.local:9092",
    ]
    "us-east-1.preprod" = [
      "kf0001.cf.prd349.preprod3.test.local:9092",
      "kf0002.cf.prd349.preprod3.test.local:9092"
    ]
  }
}
```

**Comment by macktab** [comment]
Sorry, forget to mention this, I have tried both variables.
If you try
`variable "vpc" { default = "dev" }`
for test template, you will get error
`Error: EOF
kafka: client has run out of available brokers to talk to (Is your cluster reachable?)`
Again, works with 0.2.12 version.

**Comment by Mongey** [comment]
perhaps you need to disable `tls`, or skip the verification ?

```tf
provider "kafka" {
    bootstrap_servers = var.brokers_lookup[format("%s.%s",var.aws_region,var.vpc)]
    tls_enabled       = false
    skip_tls_verify   = true
}
````

**Comment by macktab** [comment]
Thank you. Just tried with these parameters, still get error:
`Error: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)`

**Comment by macktab** [comment]
Seems, it is working with latest version of Terraform v0.14.8 .
Sorry, I have tested on old version of terraform.
Thank you.
