### ISSUE TITLE
Lazy Provider Init

### ISSUE THREAD

**Issue by maxgr0** [Mongey/terraform-provider-kafka#178]
First of all, thanks for the great work over here! Perfect idea to manage Kafka topics and ACLs using TF🏄‍♀️

When running a `terraform apply` or `terraform plan` **without** having the cluster and/or credentials created in advance, the provider fails with one of the following errors:

when using the direct output from kafka cluster module which creates the resource:
```
Error: kafka: invalid configuration (Net.SASL.Password must not be empty when SASL is enabled)
```

when using a workaround like `sasl_password = coalesce(module.k8s_cluster.password, "password")`
```
Error: kafka server: SASL Authentication failed.
```

I think this problems comes up due to a not-lazy initialization of the provider. It tries to connect to the cluster as soon as the provider gets initialized so it fails. Makes totally sense but in this context (and in comparison to other providers) this can cause errors as it's one of the benefits of TF to have the complete infrastructure created using one command.

Cheers!🍻

**Comment by nitrocode** [comment]
Looks like a good example is in the postgres provider

They have a basic NewClient function which does not connect to the resource

https://github.com/cyrilgdn/terraform-provider-postgresql/blob/9c28441b54cc54fb7caaf522486a903a93f41a98/postgresql/config.go#L151-L157

They have a separate `Connect()` function

https://github.com/cyrilgdn/terraform-provider-postgresql/blob/9c28441b54cc54fb7caaf522486a903a93f41a98/postgresql/config.go#L235

which is then used by its helper function

https://github.com/cyrilgdn/terraform-provider-postgresql/blob/34bc7327bcc5481beb990954da71ff23319bf961/postgresql/helpers.go

which is then finally used by each of its schema.Resource's Create/Read/Destroy

https://github.com/cyrilgdn/terraform-provider-postgresql/search?q=pgresourcefunc
