### ISSUE TITLE
Error: Topic with this name already exists.

### ISSUE THREAD

**Issue by joeljames** [Mongey/terraform-provider-kafka#181]
I have a Kafka Custer which already contains existing topics.

Is there a migration pattern which I should adapt to when reconfiguring the existing topics with new config?
Currently, I get the below error: 
```
 Error: kafka server: Topic with this name already exists.
   on main.tf line 10, in resource "kafka_topic" "my_topic":
```
Can I tell this plugin to update the topic config if the topic already exist?

This is the example source:
```
resource "kafka_topic" "my_topic" {
  name               = my_topic
  replication_factor = 2
  partitions         = 10

  depends_on = [kafka_acl.global]
}
```

**Comment by Mongey** [comment]
You'll need to import the exiting topics

```sh
terraform import kafka_topic.my_topic my_topic
```

**Comment by joeljames** [comment]
Thank you! I realized that after asking this question. I should have read the docs better.

**Comment by Mongey** [comment]
No problem!
