### ISSUE TITLE
Error: No bootstrap_servers provided when AWS MSK provisioned in same TF script

### ISSUE THREAD

**Issue by kopachevsky** [Mongey/terraform-provider-kafka#189]
I'm provision MSK with my custom module, and in the same set of TF files (read same state) I do have kafka provider definition:

```
provider "kafka" {
  bootstrap_servers = split(",", module.msk.bootstrap_brokers_tls)
  tls_enabled       = true
}
```

Kafka topic resources has dependency to module.msk as well
```

resource "kafka_topic" "my_topic" {
  name               = "my_topic"
  replication_factor = 2
  partitions         = 50
  depends_on         = [module.msk]
}
```

I have to comment kafka provider and corresponding topics, to provision MSK first otherwise I have error:

```
│ Error: No bootstrap_servers provided
│ 
│   with kafka_topic.my_topic,
│   on kafka_topics.tf line 15, in resource "kafka_topic" "my_topic":
│   15: resource "kafka_topic" "my_topic" {
│ 
```

Is this expected behaviour or a bug?

**Comment by haidaraM** [comment]
This is a expected behaviour. The provider needs to be initialized with the brokers information but the same brokers are created in the same Terraform workspace/script: it won't work the first time you launch your stack.

The solution is to create your topic inside another Terraform script that can fetch the `bootstrap_servers` with some data sources or Terraform remote state **after** the cluster has been created

**Comment by ivialex-mcd** [comment]
> This is a expected behaviour. The provider needs to be initialized with the brokers information but the same brokers are created in the same Terraform workspace/script: it won't work the first time you launch your stack.
> 
> The solution is to create your topic inside another Terraform script that can fetch the `bootstrap_servers` with some data sources or Terraform remote state **after** the cluster has been created

Hi @haidaraM ,

I did it and works for me. I created one pipeline to run terraform scripts and create MSK cluster. And I created second pipeline to run terraform scripts for topics, and works for me. 

Thanks.
