### ISSUE TITLE
Error upon go build

### ISSUE THREAD

**Issue by ThomasVdBerge** [Mongey/terraform-provider-kafka#19]
Hello,

Trying to build this provider so I can use it in terraform.

Upon building the provider, the following error appears

```
# _/terraform-provider-kafka
./main.go:9:45: cannot use kafka.Provider (type func() "github.com/Mongey/terraform-provider-kafka/vendor/github.com/hashicorp/terraform/terraform".ResourceProvider) as type "github.com/hashicorp/terraform/plugin".ProviderFunc in field value
go build  50.23s user 9.76s system 465% cpu 12.888 total
```

**Comment by Mongey** [comment]
👋  @ThomasVdBerge 

It seems like this is a [common][1]-[ish][2] error when building terraform providers -- and revolves around the difficulties with setting up a go environment.

Try running `go build` from `$GOPATH/src/github.com/Mongey/terraform-provider-kafka`, like so:

1. `git clone https://github.com/Mongey/terraform-provider-kafka.git $GOPATH/src/github.com/Mongey/terraform-provider-kafka`
2. `cd $GOPATH/src/github.com/Mongey/terraform-provider-kafka`
3. `go build `

[1]: https://github.com/terraform-providers/terraform-provider-aws/issues/2077
[2]: https://github.com/dmacvicar/terraform-provider-libvirt/issues/206

**Comment by Mongey** [comment]
I'm going to close this out, let me know if you're still experiencing issues and I'll reopen :)
