### ISSUE TITLE
Kafka Topic: unable to create topic mentioned in the example (probably unclear documentation)

### ISSUE THREAD

**Issue by alexkonkin** [Mongey/terraform-provider-kafka#208]
It is not possible to create a topic mentioned in the example (Linux/Ubuntu 18):
Kafka provider version is: 0.4.1

```
terraform {
  required_providers {
    kafka = {
      source = "Mongey/kafka"
    }
  }
}

provider "kafka" {
  bootstrap_servers = ["kafka1:9092"]
}

resource "kafka_topic" "logs" {
  name               = "systemd_logs"
  replication_factor = 2
  partitions         = 100

  config = {
    "segment.ms"     = "20000"
    "cleanup.policy" = "compact"
  }
}
```
The kafka cluster is configured in the vagrant virtual machines
and the list of the topics could be retrieved with the command:
`kafka-topics.sh --bootstrap-server kafka1:9092 --list`

The Kafka cluster version is:  kafka_2.12-0.10.2.1

Steps to reproduce:
-install or use terraform 0.13.5 (also replicated with the most modern version)
-create main.tf file in a separate folder
-copy-paste the snippet above that points to the actual bootstrap server in your environment
-validate that the server is available and can interact with the command line and 
  return a list of topics by executing the command
`kafka-topics.sh --bootstrap-server kafka1:9092 --list`  
-run
 terraform init to download kafka provider
-run 
 terraform plan
 
Expected behavior:
Terraform plan should execute and return some output

Actual result:
The error is shown:
Error: read tcp 172.16.97.11:37504->172.16.97.11:9092: read: connection reset by peer
kafka: client has run out of available brokers to talk to (Is your cluster reachable?)

[please take into account that the actual work of the cluster was checked with kafka-topics.sh]

In the very end of the page:
https://github.com/Mongey/terraform-provider-kafka

Is present the requirement section:
(>= Kafka 1.0.0) that redirects to the page
https://cwiki.apache.org/confluence/display/KAFKA/KIP-117%3A+Add+a+public+AdminClient+API+for+Kafka+admin+operations

Is this a bug or some steps related to the installation
of the third-pary library  kafka-clients.jar is required?

If latter, could you please give some instructions on how to install or
add this third party library to the Linux system (Ubuntu 18 etc.)

Thank you.

**Comment by alexkonkin** [comment]
In my case the setup shown in the example was not enough 
for the the AWS MSK Kafka cluster deployed with the default settings.

Below I quote the configuration of kafka provider that allowed me to create a topic
and fix the error that I mentioned above.

provider "kafka" {
  bootstrap_servers = ["xxx.c9.kafka.us-east-1.amazonaws.com:9092"]
  tls_enabled     = false
  skip_tls_verify = true
}

Thank you for this module.

**Comment by kpweiler** [comment]
@Mongey - I ran into a similar issue with a non-tls cluster (not AWS). Like @alexkonkin, I had to set `tls_enabled = false` in the provider. The documentation here (https://registry.terraform.io/providers/Mongey/kafka/latest/docs#tls_enabled) states that `tls_enabled` is `false` by default, but I don't think that's true based on this behavior.

Cheers!

**Comment by Mongey** [comment]
@kpweiler you're right, I'll update the docs
