### ISSUE TITLE
Create new release with quotas

### ISSUE THREAD

**Issue by weeco** [Mongey/terraform-provider-kafka#214]
Hey,
I was looking at the Readme and saw there's a quota resource nowadays. I gave it a shot but:

╷
│ Error: Invalid resource type
│
│   on main.tf line 6, in resource "kafka_quota" "address_service":
│    6: resource "kafka_quota" "address_service" {
│
│ The provider mongey/kafka does not support resource type "kafka_quota".
╵

I noticed the feature has been committed in oct, but a new release hasn't been created since then. Can you release a new version by any chance?

PS: Have a look at https://github.com/twmb/franz-go as replacement for Sarama. I've developed quite a few tools that use a lot of the Kafka API functionality and I can ensure that you won't look back. It's more feature complete, always more up to-date (thanks to code generation) and is generally a high quality lib. I have used Sarama before as well.

**Comment by Mongey** [comment]
Sorry for the delay, the acceptance tests were broken for a bit 😓 . Released [v0.4.2](https://github.com/Mongey/terraform-provider-kafka/releases/tag/v0.4.2)

> PS: Have a look at https://github.com/twmb/franz-go as replacement for Sarama

thanks, looks great!
