### ISSUE TITLE
SASL no TLS and AWS MSK

### ISSUE THREAD

**Issue by mattia-crypto** [Mongey/terraform-provider-kafka#258]
Hi,

I am unable to use the provider with an AWS MSK cluster configured with SASL:

```
terraform {
  required_version = ">=1.1.5"
  required_providers {
    kafka = {
      source = "Mongey/kafka"
    }
  }
}

provider "kafka" {
  bootstrap_servers = ["some-host:9096"]
  sasl_username     = var.terraform_sasl_username
  sasl_password     = var.terraform_sasl_password
  sasl_mechanism    = "scram-sha512"
  tls_enabled       = false
}
```

I keep seeing the following on `terraform apply`:

```
Error: kafka: client has run out of available brokers to talk to: unexpected EOF
```

when trying to create:

```
resource "kafka_topic" "test" {
  name               = "test"
  replication_factor = 3
  partitions         = 1

}
```

**Comment by antontreushchenko** [comment]
Try to use
provider "kafka" {
  bootstrap_servers = ["some-host:9096"]
  sasl_username     = var.terraform_sasl_username
  sasl_password     = var.terraform_sasl_password
  sasl_mechanism    = "scram-sha512"
  tls_enabled       = true
  skip_tls_verify   = false
}

**Comment by mattia-crypto** [comment]
@antontreushchenko  Same problem unfortunately

**Comment by antontreushchenko** [comment]
![image](https://user-images.githubusercontent.com/100796409/170138304-3bf5b4fa-c8fc-4c7f-bfbb-bf8d77150c35.png)
![Untitled](https://user-images.githubusercontent.com/100796409/170138563-563dba98-7d3b-46a3-96a3-3564e8adc745.png)
![Untitled](https://user-images.githubusercontent.com/100796409/170138691-d4ce29f0-6e15-4068-99fb-d2eed3de359d.png)

I have such a security configuration for the cluster, if yours is not like this, then try to do this

**Comment by mattia-crypto** [comment]
@antontreushchenko  on second note, I noticed I had overlooked one of the params in the config you sent. I managed to make it work now with this:

```
provider "kafka" {
  bootstrap_servers = ["some-host:9096"]
  sasl_username     = var.terraform_sasl_username
  sasl_password     = var.terraform_sasl_password
  sasl_mechanism    = "scram-sha512"
  tls_enabled       = true
  skip_tls_verify   = false
}
```

**Comment by rssaini01** [comment]
I'm bit curious to know,, why you guys are using private port like 9096 ?? it's a private endpoint port for SASL/SCRAM.
