### ISSUE TITLE
Allow configurable timeout for modifying a topic

### ISSUE THREAD

**Issue by csghuser** [Mongey/terraform-provider-kafka#26]
Is it possible to allow this 10 second value to be configurable by the user?

https://github.com/Mongey/terraform-provider-kafka/blob/58ad61960e3e4e7db1e17908a48b6e8a2fc0f600/kafka/resource_kafka_topic.go#L92

**Comment by Mongey** [comment]
👋 @csghuser 10 seconds is probably too low a default anyway. I'll increase the default timeout, and look at making it configurable.

**Comment by csghuser** [comment]
@Mongey thank you! 🙂
