### ISSUE TITLE
Unable to destroy, or add further changes

### ISSUE THREAD

**Issue by mattia-crypto** [Mongey/terraform-provider-kafka#261]
I was able to create the following ACLs and topics:

```
module.kafka.kafka_acl.this["terraform-cluster-admin"]
module.kafka.kafka_acl.this["terraform-topic-admin"]
module.kafka.kafka_topic.this["fork"]
module.kafka.kafka_topic.this["mock"]
module.kafka.kafka_topic.this["raw"]
```

However, whenever I am now trying to execute `terraform plan`, I get the following error:

```
╷
│ Error: kafka: client has run out of available brokers to talk to: 2 errors occurred:
│ 	* EOF
│ 	* EOF
```

This means I am unable to even execute `terraform destroy` on any other resources defined in the same module.

**Comment by Mongey** [comment]
@mattia-crypto can you please provider the config that you're using. 

I would guess that you have locked out the terraform client after enabling ACLs

**Comment by mattia-crypto** [comment]
@Mongey yep you were right! Pardon the delay, but was abroad.
