### ISSUE TITLE
Can't specify key and certificate as environment variables.

### ISSUE THREAD

**Issue by iluwaa** [Mongey/terraform-provider-kafka#299]
When I am trying to specify key/certificate as KAFKA_CLIENT_CERT/KAFKA_CLIENT_KEY getting error:
` Error: open -----BEGIN PRIVATE KEY-----\nXXXXX\n-----END PRIVATE KEY-----\n: file name too long`
but if I am specifying client_cert/client_key in provider config - all works like expected.

**Comment by gopkri24** [comment]
Replace `\n` with newline and your issue should be fixed. Something like this:

`export KAFKA_CA_CERT="-----BEGIN CERTIFICATE-----
asdasdasdasdasdasdasfadfsfdgdfgdghfgnbseoitghi 4JTPGwnpgnvspfnvp
asdasdasdasdasdasdasfadfsfdgdfgdghfgnbseoitghi 4JTPGwnpgnvspfnvp
...
........
asdasdasdasdasdasdasfadfsfdgdfgdghfgnbseoitghi 4JTPGwnpgnvspfnvp
-----END CERTIFICATE-----"`

**Comment by iluwaa** [comment]
that works,
