### ISSUE TITLE
Error when connecting to cluster with many brokers

### ISSUE THREAD

**Issue by jeqo** [Mongey/terraform-provider-kafka#31]
When executing an action like update topic, it is failing if the first broker available is not the controller:

```
kafka_topic.topic1: topic1: kafka server: This is not the correct controller for this cluster.
```

Using `client.Controller()` to get controller instead of checking for available broker will solve this.

I have give a try: https://github.com/sysco-middleware/terraform-provider-kafka-1/commit/038d4b70569caf693aceadf6efd9ae333a44d5a5 Happy to create a PR if make sense.

**Comment by Mongey** [comment]
@jeqo Thanks for reporting this, please create a PR 👍 

I'll look into adding multiple brokers to the CI setup, maybe that would have caught this.

**Comment by jeqo** [comment]
Is a tough one to check as Controller is not deterministic AFAIK, probably starting first one node, and then a second one, and only point to the second one would be a way to test it.

**Comment by opsj** [comment]
@Mongey @jeqo I'm still experiencing this issue with the `terraform-provider-kafka_0.1.1` release. Is said bug fix included in that release?
