### ISSUE TITLE
Confluent Cloud. Error: kafka: client has run out of available brokers to talk to: EOF

### ISSUE THREAD

**Issue by Jokba** [Mongey/terraform-provider-kafka#321]
I'm trying to create topics on my Confluent Cloud kafka cluster using this provider. Terraform plan looks shows the right change however when I apply it, I get this error.
**Error: kafka: client has run out of available brokers to talk to: EOF**

This is my code
```
terraform {
  required_providers {
    kafka = {
      source = "Mongey/kafka"
      version = "0.5.2"
    }
  }
}

provider "kafka" {
  bootstrap_servers = ["cluster-id.ca-central-1.aws.confluent.cloud:9092"]
  skip_tls_verify   = true
  tls_enabled = false
  sasl_mechanism = "plain"
  sasl_username = "redacted" #kafka cluster api key with global access
  sasl_password = "redacted" #kafka cluster api secret
}

locals {
  kafka-topics = [
    {
    name = "topic.token"
    }
  ]
}

resource "kafka_topic" "topic_token" {

  for_each = {
    for topic in local.kafka-topics : "${topic.name}" => topic
  }

  name				= "${each.value.name}.env"
  replication_factor		= 3 #var.replication_factor
  partitions			= 6 #var.partitions
  config = {
	"retention.ms"		 = 190000 #var.retention_policy
  }
}
```

I'm trying to avoid usign the confluent cloud provider as our code is already with this provider.

Thank you.

**Comment by Mongey** [comment]
Should tls_enabled be true here?

**Comment by Jokba** [comment]
I don't know why I didn't try that but that seems to have worked. Thank you!

I'll most likely discover issues but for now the plan is to use this provider for kafka topics and ACL only. Other resources, I'll use confluent cloud provider
