### ISSUE TITLE
Sarama looking for new maintainers

### ISSUE THREAD

**Issue by OneCricketeer** [Mongey/terraform-provider-kafka#328]
Refer to https://github.com/Shopify/sarama/issues/2461 for discussion

**Comment by bboggs-agi-digital** [comment]
@Mongey Are there plans to move to confluent-kafka-go?

**Comment by Mongey** [comment]
> @Mongey Are there plans to move to confluent-kafka-go?

No, not currently anyway.

Could potentially move to that or franz-go
