### ISSUE TITLE
Add support for oauthbearer as the sasl mechanism

### ISSUE THREAD

**Issue by kmdlcp** [Mongey/terraform-provider-kafka#377]
Oauthbearer is one of the sasl mechanisms supported by Kafka. It would be great if you also supported this.

**Comment by kmdlcp** [comment]
If i make a pull request that supports this, will you be willing to approve it rather quickly? Assuming that you don't find problems with the PR?

**Comment by Mongey** [comment]
> If i make a pull request that supports this, will you be willing to approve it rather quickly? Assuming that you don't find problems with the PR?

If there's sufficient tests around it, yep

**Comment by kmdlcp** [comment]
I made the PR:

https://github.com/Mongey/terraform-provider-kafka/pull/379

**Comment by Spragalas** [comment]
https://github.com/Mongey/terraform-provider-kafka/pull/384

update code to allow specifying aws profile

**Comment by kmdlcp** [comment]
> #384
> 
> update code to allow specifying aws profile

These are separate issues! This issue calls for generic OAuth support. Which i implemented in #379
The Aws is a specific OAuth, that should be handeled seperately.

**Comment by kmdlcp** [comment]
Closing this issue as it has been complete with the merge of PR #379
