### ISSUE TITLE
Allow resource pattern type to be set when managing ACLs

### ISSUE THREAD

**Issue by dmazhar-cogniance** [Mongey/terraform-provider-kafka#38]
Hi! Thanks for the awesome provider!
One thing that I'm missing in the ACL resource is an option ot set the `resource-pattern-type`. This allows to define ACLs with topic prefixes for example. So instead of creating the ACL with topic name I can set the topic prefix only. This is described in Kafka documentation: https://kafka.apache.org/documentation/#security_authz_cli (see `--resource-pattern-type` option).

It looks like implementing this would be tricky as sarama does not support this yet, am I right?

**Comment by Mongey** [comment]
> Hi! Thanks for the awesome provider!

You're welcome!

> It looks like implementing this would be tricky as sarama does not support this yet, am I right?

You're correct, `resource-pattern-type` was added in [v1 of CreateACLRequest](https://kafka.apache.org/protocol#The_Messages_CreateAcls), and sarama only [supports v0](https://github.com/Shopify/sarama/blob/97315fefd9d1a91fbc682c52c44fcb490fa5c6e7/acl_create_request.go#L43-L45).

It's a pretty small change to the protocol -- I should be able to implement it in sarama and support it in this provider. The only tricky part will be optionally supporting this based on the version of Kafka that's targeted -- as `resource-pattern-type` only has an effect on Kafka 2.0 and above.

**Comment by Mongey** [comment]
> Another option will be to pass kafka version in the provider 🤔

👍  I'll probably go with this

📝 I've started on the sarama changes over @ https://github.com/Shopify/sarama/pull/1236. It's a bit more work than expected, as it requires updating `Describe` &  `Delete` alongside `Create`.
