### ISSUE TITLE
Empty Summary: This is always a bug in the provider and should be reported to the provider developers

### ISSUE THREAD

**Issue by mr92752** [Mongey/terraform-provider-kafka#425]
Hi, every time I run my config, provider detects a change in kafka topic config and tries to modify it though there is not any change. Eventually it fails to modify it and throws me that error. I think the provider is not detecting the state properly.

This is the plan 

 # kafka_topic.kafka_topics[0] will be updated in-place
  ~ resource "kafka_topic" "kafka_topics" {
      ~ config             = {
          + "cleanup.policy" = "compact"
          + "segment.ms"     = "20000"
        }
        id                 = "MSKTestTopic-20240529"
        name               = "MSKTestTopic-20240529"
        # (2 unchanged attributes hidden)
    }

  # kafka_topic.kafka_topics[1] will be updated in-place
  ~ resource "kafka_topic" "kafka_topics" {
      ~ config             = {
          + "cleanup.policy" = "compact"
          + "segment.ms"     = "20000"
        }
        id                 = "MSKTestTopic-20240530"
        name               = "MSKTestTopic-20240530"
        # (2 unchanged attributes hidden)
    }

Plan: 0 to add, 2 to change, 0 to destroy.

and the error messages

kafka_topic.kafka_topics[1]: Modifying... [id=MSKTestTopic-20240530]
kafka_topic.kafka_topics[0]: Modifying... [id=MSKTestTopic-20240529]
╷
│ Error: Empty Summary: This is always a bug in the provider and should be reported to the provider developers.
│
│   with kafka_topic.kafka_topics[1],
│   on kafka-topics.tf line 4, in resource "kafka_topic" "kafka_topics":
│    4: resource "kafka_topic" "kafka_topics" {
│
╵
╷
│ Error: Empty Summary: This is always a bug in the provider and should be reported to the provider developers.
│
│   with kafka_topic.kafka_topics[0],
│   on kafka-topics.tf line 4, in resource "kafka_topic" "kafka_topics":
│    4: resource "kafka_topic" "kafka_topics" {
│
╵

is it possible to check this or is there any work around?

**Comment by qq304635576** [comment]
@mr92752 
I figured out the root cause that is the IAM permissions issue if your connect MSK cluster with IAM role-based authentication. pls add IAM policy as below, this error could be fixed:


```
resource "aws_iam_role_policy" "app_exchange_msk_admin_policy" {
  name = "app_exchange_msk_admin_policy"
  role = aws_iam_role.app_exchange_msk_admin.name

  policy = <<EOF
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "kafka:*"
            ],
            "Resource": "arn:aws:kafka:ap-northeast-1:XXXXXXXXXXXXXX:/*"
        },
        {
            "Action": [
                "kafka-cluster:*"
            ],
            "Effect": "Allow",
            "Resource": "arn:aws:kafka:ap-northeast-1:XXXXXXXXXXXXXXXXX:cluster/pl-exchange-dev-msk/d0-514551b42a-462e-8e21-915e7216fbd6-3"
        },
        {
            "Action": [
                "kafka-cluster:*"
            ],
            "Effect": "Allow",
            "Resource": "arn:aws:kafka:ap-northeast-1:XXXXXXXXXXXXX:topic/pl-exchange-dev-msk/d0-514551b42a-462e-8e21-915e7216fbd6-3/*"
        },
        {
            "Action": [
                "kafka-cluster:*"
            ],
            "Effect": "Allow",
            "Resource": "arn:aws:kafka:ap-northeast-1:XXXXXXXXXXXXXX:group/pl-exchange-dev-msk/d0-514551b42a-462e-8e21-915e7216fbd6-3/*"
        }
    ]
}
EOF
}

```
