### ISSUE TITLE
Terraform 0.11 or 0.12?

### ISSUE THREAD

**Issue by ehrlichja** [Mongey/terraform-provider-kafka#47]
Just wonder what is the state of terraform 0.12 compatibility?

Thank you very much for the wonderful provider!

**Comment by Mongey** [comment]
The current version of the provider is built for 0.11. 

I have the changes for 0.12 over in #48 
I'm not sure if 0.12 providers are backwards compatible, so I'll hold off on merging + releasing until terraform 0.12 is out.

If you want to use the provider with 0.12 you can grab the linux binary from the CI build over @ 
https://372-103748731-gh.circle-artifacts.com/0/terraform-provider-kafka

**Comment by ehrlichja** [comment]
Thanks!
