### ISSUE TITLE
 Chicken and Egg

### ISSUE THREAD

**Issue by paulca99** [Mongey/terraform-provider-kafka#52]
Got a tricky little issue when using it on a experimental development cluster. If you build up a development kafka cluster using terraform EC2 instances, then add a bunch of topics using this provider, then decide you've screwed up the EC2 instances running kafka, so tweak your EC2 terraform,  and terminate all the cluster instances, then run terraform apply to re-create them,  this provider cannot connect to the cluster, so causes the tf apply to fail, you therefore can't recreate the cluster. You can't even apply any unrelated changes. The only way I could find around this was to manually unpick all the kafka resources from the state file.

 I've never done a custom provider, so this could be a load of rubbish, but is there a way to allow all the other TF resources to apply (EC2 create) before even attempting to check the kafka topics ?

**Comment by Mongey** [comment]
👋 @paulca99 I don't believe this is an issue with this particular provider; and is more of a terraform question.
When destroying the cluster, doing a `terraform destroy` should remove the topics, then destroy the ec2 instances. If you are rotating the instances outside of terraform, doing a `terraform refresh` once the new cluster is up, should be enough to get terraform to notice that the topics don't exist on the new kafka cluster; and a subsequent plan and apply should work.

**Comment by paulca99** [comment]
I can't do a terraform destroy as there's a load of other resources in the same env that I don't want to destroy. TBH I've just had 2 weeks off work and it's a bit fuzzy in my head, I'll try the refresh route on Monday when I go back in, but I think once the EC2 instances had been destroyed outside terraform , and the provider couldn't create a connection to kafka I was snookered because I couldn't re-create the cluster with a terraform apply... but I never tried the refresh, so I'll try that first...ta.

**Comment by Mongey** [comment]
Going to close this out as there's not much I can fix here 😄
