### ISSUE TITLE
Increasing replication factor recreates the topic

### ISSUE THREAD

**Issue by davidmarkstartapp** [Mongey/terraform-provider-kafka#53]
Hi @Mongey 

Thanks for this amazing provider!
We started to implement it and noticed that increasing replication factor force recreation of the topics although this very uncommon operation, this is something we will want to be able change it easily in case we made a mistake or business priorities.

Can you help?
Thanks
D.

**Comment by Mongey** [comment]
👋  @davidmarkstartapp 

I'll need to do some investigation to see if it's now possible, but my current understanding is that the Kafka protocol does not expose a way of increasing the replication factor; and as such we can't implement it in the provider.

Looking at `kafka-reassign-partitions.sh`, (which is the typical way people increase the replication-factor), it seems to interact directly with zookeeper, and that's not something I want to do.

**Comment by davidmarkstartapp** [comment]
Yes, we used to change it with kafka-manager but need to check if it use kafka / zk behind the scene to complete this operation.

Thanks

**Comment by MattPumphrey** [comment]
What about using the kafka-topics.sh script?  https://kafka.apache.org/081/documentation.html#basic_ops_modify_topic

**Comment by Mongey** [comment]
Maybe this is now possible via the Kafka Protocol with [`AlterPartitionReassignments`](https://kafka.apache.org/protocol#The_Messages_AlterPartitionReassignments)

**Comment by jay7x** [comment]
Is there any chance to have this? 🙏

**Comment by SahilKang** [comment]
I've hacked [PR #148](https://github.com/Mongey/terraform-provider-kafka/pull/148) together to address this.
It's a WIP, though (I haven't tested or anything)

**Comment by SahilKang** [comment]
Okay, I've lifted the WIP flag for [PR #148](https://github.com/Mongey/terraform-provider-kafka/pull/148)

The normal `docker-compose up` :whale: workflow from the README still works, so feel free to play around with it locally

**Comment by Mongey** [comment]
This should be available in the `v0.3.0` release.
