### ISSUE TITLE
Provision topics with a Zookeeper provider

### ISSUE THREAD

**Issue by edify42** [Mongey/terraform-provider-kafka#57]
The tooling only supports connecting to an array of brokers. We use zookeeper with JAAS auth to create topics (internally I think kafka-acl.sh gets a kafka broker directly to create the topic?)

Would be nice if this TF provider was able to use Zookeeper instead to provision topics and ACLs to replaces our commands:

`kafka-acls.sh --authorizer-properties zookeeper.connect=$ZOOKEEPER --list`
`kafka-topics.sh --create --zookeeper $ZOOKEEPER --replication-factor 3 --partitions 1 --topic my-topic`

**Comment by Mongey** [comment]
👋  Hey @edify42, sorry for the delay. Can you explain why you would want to connect via zookeeper, rather than talking directly to Kafka?

**Comment by edify42** [comment]
Hey @Mongey - we have a multi broker kafka deployment which we setup from [Confluent documentation](https://docs.confluent.io/current/kafka/authorization.html) The kafka metadata is managed by Zookeeper and the out-of-the-box scripts provided in the kafka docs suggest we connect with zookeeper to manage things like topic creation and ACLs. Ideally we'd do it all via this TF provider so I think there's a requirement to connect to Zookeeper instead of Kafka directly.

**Comment by Mongey** [comment]
Topics and ACLs can be managed through the Kafka broker, and therefore via this provider, there’s no need to connect to zookeeper. 

I’m going to close this out, I didn’t intend to support anything that is enabled by fudging configs in zookeeper to make Kafka do something. Those feature requests should happen in apache/Kafka and expose functionality via the api for others (this provider) to use.
