### ISSUE TITLE
Externally deleted ACLs are not detected as missing

### ISSUE THREAD

**Issue by bitzstein** [Mongey/terraform-provider-kafka#61]
I would like the ACL resource to recreate any missing ACLs, if they are deleted externally.

Currently it appears that the `func aclRead(d *schema.ResourceData, meta interface{}) error` implementation only relies on the Terraform state, rather than doing any state modifications based on the result of `ListACLs`. So missing ACLs are currently not detected.

**Comment by stevie-** [comment]
https://github.com/Mongey/terraform-provider-kafka/pull/65

Will fix this issue

**Comment by Mongey** [comment]
Released in [0.2.5](https://github.com/Mongey/terraform-provider-kafka/releases/tag/v0.2.5)
https://github.com/Mongey/terraform-provider-kafka/issues/109#issuecomment-622387411
