### ISSUE TITLE
Error during "go build" with tag v0.2.1

### ISSUE THREAD

**Issue by kdefives** [Mongey/terraform-provider-kafka#69]
Hello,

Trying to build this provider by using version tag v0.2.1 and it raise an error (detailled steps below). There is no problem with master branch and version tag v0.2.0. I tested with another laptop on Mac and Linux, exactly same error message.

`> git status`
`HEAD detached at v0.2.1`
`nothing to commit, working tree clean`

`> make build`
`go build .`

The error message is:
`github.com/Mongey/terraform-provider-kafka/kafka
kafka/config.go:33:24: kafkaConfig.Net.SASL.SCRAMClientGeneratorFunc undefined (type struct { Enable bool; Mechanism sarama.SASLMechanism; Handshake bool; User string; Password string; SCRAMAuthzID string; SCRAMClient sarama.SCRAMClient; TokenProvider sarama.AccessTokenProvider } has no field or method SCRAMClientGeneratorFunc)
kafka/config.go:36:24: kafkaConfig.Net.SASL.SCRAMClientGeneratorFunc undefined (type struct { Enable bool; Mechanism sarama.SASLMechanism; Handshake bool; User string; Password string; SCRAMAuthzID string; SCRAMClient sarama.SCRAMClient; TokenProvider sarama.AccessTokenProvider } has no field or method SCRAMClientGeneratorFunc)
GNUmakefile:6: recipe for target 'build' failed
make: *** [build] Error 2`

**Comment by Mongey** [comment]
Hi @kdefives can you try with master ? 
I think the `/vendor` folder didn't quite line up with that was in `go.mod` / `go.sum` in `v0.2.1`
alternatively you could `GO111MODULE=on go build .`

**Comment by kdefives** [comment]
@Mongey With master it is working correctly too. 

For the moment I will use v0.2.0 but let me know if you plan to release a version v0.2.2 from master branch. In this case i think I could use this v0.2.2. 
I did not use the master branch because i do not know if master branch is stable enough for production environments.

I prefer to use v0.2.0 because i compile everything in my CICD pipeline and i use "CGO_ENABLED=0 go build..." for all my providers compilation. I prefer to not add something specific for only one provider.

Thx

**Comment by Mongey** [comment]
@kdefives I released v0.2.2 with the changes. Hopefully that resolves the issue.

**Comment by kdefives** [comment]
I confirm @Mongey ! Thx
