### ISSUE TITLE
kafka_acl acl_operation to take a list 

### ISSUE THREAD

**Issue by gergelysotidm** [Mongey/terraform-provider-kafka#84]
to mimick a producer, one needs describe, write and create actions on a topic. It would be nice if the `kafka_acl` resource could take a list of operations, because currently one needs to replicate the resource with the different operations

**Comment by Mongey** [comment]
Hey @gergelysotidm can you provide an example of what a config like this looks like currently and what a proposed syntax would be, thanks!

**Comment by Mongey** [comment]
Seems somewhat related to #70 in solving the common producer / consumer acl configs

**Comment by gergelysotidm** [comment]
Hi @Mongey 
Here is how it could look like:

```
resource "kafka_acl" "groups_read" {
  resource_name = "my-group"
  resource_type = "Group"
  acl_principal = "myuser"
  acl_host = "*"
  acl_operation = ["Read", "Describe"]
  acl_permission_type = "Allow"
}
```
Today, one needs to duplicate this resource, one fore each acl_operation.
Indeed, this is related to #70 , but I think once we have this, the produces-consumer can become an alias to a set of operations.

**Comment by evsasha** [comment]
Hello @gergelysotidm , you can use loop:

```
resource "kafka_acl" "groups" {
  for_each = {
    acl1 = "Read"
    acl2 = "Write"
    acl3 = "Describe"
  }
  resource_name = "my-group"
  resource_type = "Group"
  acl_principal = "myuser"
  acl_host = "*"
  acl_operation = each.value
  acl_permission_type = "Allow"
}
```
