### ISSUE TITLE
Error Opening Certificates for Provider - file name too long

### ISSUE THREAD

**Issue by joshbranham** [Mongey/terraform-provider-kafka#96]
I am hitting an error when trying to open the certificates needed to connect to my clusters. The error to me seems like the provider is trying to open the contents of the file as a file path?

```
Error: open -----BEGIN CERTIFICATE-----
<certificate redacted>
-----END CERTIFICATE-----
: file name too long
```

My provider config is:
```
provider "kafka" {
  version           = "~> 0.2"
  bootstrap_servers = ["production-kafka.<redacted>:9093"]
  ca_cert           = file("/home/ca.crt")
  client_cert       = file("/home/client.crt")
  client_key        = file("/home/private.key")
}
```

**Comment by Mongey** [comment]
👋 Hey @joshbranham , what version of the provider are you using? Prior to v`0.2.3` the `ca_cert` etc took a path, which, as you said it looks like it's attempting to do that.
 
If you're not using the latest version, I think you'll need something like this....
```
provider "kafka" {
  version           = "~> 0.2"
  bootstrap_servers = ["production-kafka.<redacted>:9093"]
  ca_cert           = "/home/ca.crt"
  client_cert       = "/home/client.crt"
  client_key        = "/home/private.key"
}
```

If you are using the `0.2.3` version, and this is happening, it's a bug

**Comment by joshbranham** [comment]
@Mongey I am using `0.2.3`

**Comment by joshbranham** [comment]
also fwiw I am just using certificate files on disk (running in Atlantis) and I tried moving the files to shorter paths with no luck so I am pretty sure its doing something funky like trying to load the contents of the file as the path or something?

**Comment by MattPumphrey** [comment]
We installed the Kafka provider into our atlantis docker container to be able to execute this.  I hope that helps with that.

**Comment by joshbranham** [comment]
> We installed the Kafka provider into our atlantis docker container to be able to execute this. I hope that helps with that.

Yeah I have that part down, its more the SSL error. What version are you using? Did 0.2.2 work for you?

**Comment by Mongey** [comment]
> also fwiw I am just using certificate files on disk (running in Atlantis) and I tried moving the files to shorter paths with no luck so I am pretty sure its doing something funky like trying to load the contents of the file as the path or something?

We do have some tests that are loading in certs with files, so I'm a bit surprised
https://github.com/Mongey/terraform-provider-kafka/blob/0f186dd04a3819df8b8201c9014be660326877d3/kafka/resource_kafka_acl_test.go#L147-L152

@joshbranham can you use `terraform console` to make sure the files are being loaded correctly?

Also debug logs might help track down some issues. `TF_LOG=debug terraform plan`

**Comment by joshbranham** [comment]
I found one issue with my private key being formatted wrong and fixed that..sorry for the confusion. Now looking at `Error connecting to kafka kafka: client has run out of available brokers to talk to (Is your cluster reachable?)` which could be a transport issue. 

It was weird that the error above about opening the file was not my private key but the client cert. That library seems to be giving an odd error back?

**Comment by joshbranham** [comment]
Closing this, the issue was we are using a ELB in TCP mode that points to all kafka brokers in order to easily discover the brokers. For instance `production-kafka.dns.com` points to ELB that then forwards to all the brokers on the same port. For some reason that is not working, I will dig some more into that but it is probably something in https://github.com/shopify/sarama

Thanks for your time @Mongey
